/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "surface-container-high": "#e8e8e8",
        "primary-container": "#2e7d32",
        "primary-fixed": "#a3f69c",
        "on-surface-variant": "#40493d",
        "secondary-fixed-dim": "#fabd00",
        "secondary-fixed": "#ffdf9e",
        "error-container": "#ffdad6",
        "surface-variant": "#e2e2e2",
        error: "#ba1a1a",
        "inverse-on-surface": "#f1f1f1",
        "inverse-surface": "#2f3131",
        "primary-fixed-dim": "#88d982",
        "tertiary-fixed-dim": "#ffb3ac",
        background: "#f9f9f9",
        "tertiary-container": "#d02d2d",
        "on-primary": "#ffffff",
        "on-surface": "#1a1c1c",
        "on-secondary-fixed": "#261a00",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f9f9f9",
        "on-tertiary-fixed-variant": "#930010",
        "inverse-primary": "#88d982",
        "on-tertiary-fixed": "#410003",
        "surface-container-low": "#f3f3f3",
        "outline-variant": "#bfcaba",
        "on-secondary-container": "#6c5000",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#5b4300",
        "surface-container-highest": "#e2e2e2",
        "on-primary-fixed-variant": "#005312",
        "secondary-container": "#fdc003",
        "on-primary-container": "#cbffc2",
        "surface-container": "#eeeeee",
        primary: "#0d631b",
        surface: "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        secondary: "#785900",
        "on-tertiary-container": "#ffedeb",
        "tertiary-fixed": "#ffdad6",
        "on-background": "#1a1c1c",
        "surface-tint": "#1b6d24",
        "on-secondary": "#ffffff",
        tertiary: "#ac0c18",
        "on-primary-fixed": "#002204",
        "surface-dim": "#dadada",
        outline: "#707a6c",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "12px",
        xl: "32px",
        lg: "24px",
        md: "16px",
        base: "4px",
        sm: "12px",
        xs: "8px",
        "safe-area-margin": "16px",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "title-lg": ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "kpi-display": ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-reg": ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "label-caps": ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      fontSize: {
        "title-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "kpi-display": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-reg": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
